USE esun;
CREATE TABLE `seatingchart` (
  `FLOOR_SEAT_SEQ` int NOT NULL AUTO_INCREMENT,
  `FLOOR_NO` varchar(10) NOT NULL,
  `SEAT_NO` varchar(10) NOT NULL,
  PRIMARY KEY (`FLOOR_SEAT_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
